[metadata]
name = "aur"
description = "List and install AUR packages"
requirements = [ "pacman", "paru",]

[source]
command = "paru -Sl"
output = "{split: :1}"

[preview]
command = "paru -Si '{split: :1}' 2>/dev/null"

[keybindings]
enter = "actions:install"

[actions.install]
description = "Install the selected package"
command = "paru -S '{split: :1}'"
mode = "execute"
